const std = @import("std");

pub fn registerSupportedModelsFromTs(registry: anytype) !void {
    try registry.register(.{
        .id = "amazon.nova-2-lite-v1:0",
        .name = "Nova 2 Lite",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.33, .output = 2.75, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "amazon.nova-lite-v1:0",
        .name = "Nova Lite",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.06, .output = 0.24, .cache_read = 0.015, .cache_write = 0 },
        .context_window = 300000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "amazon.nova-micro-v1:0",
        .name = "Nova Micro",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.035, .output = 0.14, .cache_read = 0.00875, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "amazon.nova-premier-v1:0",
        .name = "Nova Premier",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 2.5, .output = 12.5, .cache_read = 0, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "amazon.nova-pro-v1:0",
        .name = "Nova Pro",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.8, .output = 3.2, .cache_read = 0.2, .cache_write = 0 },
        .context_window = 300000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "amazon.titan-text-express-v1",
        .name = "Titan Text G1 - Express",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.2, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "amazon.titan-text-express-v1:0:8k",
        .name = "Titan Text G1 - Express",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.2, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-5-haiku-20241022-v1:0",
        .name = "Claude Haiku 3.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.8, .output = 4, .cache_read = 0.08, .cache_write = 1 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-5-sonnet-20240620-v1:0",
        .name = "Claude Sonnet 3.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-5-sonnet-20241022-v2:0",
        .name = "Claude Sonnet 3.5 v2",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-7-sonnet-20250219-v1:0",
        .name = "Claude Sonnet 3.7",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-haiku-20240307-v1:0",
        .name = "Claude Haiku 3",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.25, .output = 1.25, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-opus-20240229-v1:0",
        .name = "Claude Opus 3",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 15, .output = 75, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "anthropic.claude-3-sonnet-20240229-v1:0",
        .name = "Claude Sonnet 3",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "anthropic.claude-haiku-4-5-20251001-v1:0",
        .name = "Claude Haiku 4.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "anthropic.claude-opus-4-1-20250805-v1:0",
        .name = "Claude Opus 4.1",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "anthropic.claude-opus-4-20250514-v1:0",
        .name = "Claude Opus 4",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "anthropic.claude-opus-4-5-20251101-v1:0",
        .name = "Claude Opus 4.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "anthropic.claude-opus-4-6-v1",
        .name = "Claude Opus 4.6",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "anthropic.claude-sonnet-4-20250514-v1:0",
        .name = "Claude Sonnet 4",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "anthropic.claude-sonnet-4-5-20250929-v1:0",
        .name = "Claude Sonnet 4.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "cohere.command-r-plus-v1:0",
        .name = "Command R+",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "cohere.command-r-v1:0",
        .name = "Command R",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.5, .output = 1.5, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "deepseek.r1-v1:0",
        .name = "DeepSeek-R1",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 1.35, .output = 5.4, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "deepseek.v3-v1:0",
        .name = "DeepSeek-V3.1",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.58, .output = 1.68, .cache_read = 0, .cache_write = 0 },
        .context_window = 163840,
        .max_tokens = 81920,
    });
    try registry.register(.{
        .id = "eu.anthropic.claude-haiku-4-5-20251001-v1:0",
        .name = "Claude Haiku 4.5 (EU)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "eu.anthropic.claude-opus-4-5-20251101-v1:0",
        .name = "Claude Opus 4.5 (EU)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "eu.anthropic.claude-opus-4-6-v1",
        .name = "Claude Opus 4.6 (EU)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "eu.anthropic.claude-sonnet-4-20250514-v1:0",
        .name = "Claude Sonnet 4 (EU)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
        .name = "Claude Sonnet 4.5 (EU)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "global.anthropic.claude-haiku-4-5-20251001-v1:0",
        .name = "Claude Haiku 4.5 (Global)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "global.anthropic.claude-opus-4-5-20251101-v1:0",
        .name = "Claude Opus 4.5 (Global)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "global.anthropic.claude-opus-4-6-v1",
        .name = "Claude Opus 4.6 (Global)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "global.anthropic.claude-sonnet-4-20250514-v1:0",
        .name = "Claude Sonnet 4 (Global)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        .name = "Claude Sonnet 4.5 (Global)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "google.gemma-3-27b-it",
        .name = "Google Gemma 3 27B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.12, .output = 0.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 202752,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "google.gemma-3-4b-it",
        .name = "Gemma 3 4B IT",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.04, .output = 0.08, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-1-70b-instruct-v1:0",
        .name = "Llama 3.1 70B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.72, .output = 0.72, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-1-8b-instruct-v1:0",
        .name = "Llama 3.1 8B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.22, .output = 0.22, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-2-11b-instruct-v1:0",
        .name = "Llama 3.2 11B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.16, .output = 0.16, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-2-1b-instruct-v1:0",
        .name = "Llama 3.2 1B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.1, .output = 0.1, .cache_read = 0, .cache_write = 0 },
        .context_window = 131000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-2-3b-instruct-v1:0",
        .name = "Llama 3.2 3B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.15, .cache_read = 0, .cache_write = 0 },
        .context_window = 131000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-2-90b-instruct-v1:0",
        .name = "Llama 3.2 90B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.72, .output = 0.72, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama3-3-70b-instruct-v1:0",
        .name = "Llama 3.3 70B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.72, .output = 0.72, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "meta.llama4-maverick-17b-instruct-v1:0",
        .name = "Llama 4 Maverick 17B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.24, .output = 0.97, .cache_read = 0, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "meta.llama4-scout-17b-instruct-v1:0",
        .name = "Llama 4 Scout 17B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.17, .output = 0.66, .cache_read = 0, .cache_write = 0 },
        .context_window = 3500000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "minimax.minimax-m2",
        .name = "MiniMax M2",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.3, .output = 1.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 204608,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "minimax.minimax-m2.1",
        .name = "MiniMax M2.1",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.3, .output = 1.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 204800,
        .max_tokens = 131072,
    });
    try registry.register(.{
        .id = "mistral.ministral-3-14b-instruct",
        .name = "Ministral 14B 3.0",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.2, .output = 0.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "mistral.ministral-3-8b-instruct",
        .name = "Ministral 3 8B",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.15, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "mistral.mistral-large-2402-v1:0",
        .name = "Mistral Large (24.02)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.5, .output = 1.5, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "mistral.voxtral-mini-3b-2507",
        .name = "Voxtral Mini 3B 2507",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.04, .output = 0.04, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "mistral.voxtral-small-24b-2507",
        .name = "Voxtral Small 24B 2507",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.35, .cache_read = 0, .cache_write = 0 },
        .context_window = 32000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "moonshot.kimi-k2-thinking",
        .name = "Kimi K2 Thinking",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.6, .output = 2.5, .cache_read = 0, .cache_write = 0 },
        .context_window = 256000,
        .max_tokens = 256000,
    });
    try registry.register(.{
        .id = "moonshotai.kimi-k2.5",
        .name = "Kimi K2.5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.6, .output = 3, .cache_read = 0, .cache_write = 0 },
        .context_window = 256000,
        .max_tokens = 256000,
    });
    try registry.register(.{
        .id = "nvidia.nemotron-nano-12b-v2",
        .name = "NVIDIA Nemotron Nano 12B v2 VL BF16",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.2, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "nvidia.nemotron-nano-9b-v2",
        .name = "NVIDIA Nemotron Nano 9B v2",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.06, .output = 0.23, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "openai.gpt-oss-120b-1:0",
        .name = "gpt-oss-120b",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "openai.gpt-oss-20b-1:0",
        .name = "gpt-oss-20b",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.07, .output = 0.3, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "openai.gpt-oss-safeguard-120b",
        .name = "GPT OSS Safeguard 120B",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "openai.gpt-oss-safeguard-20b",
        .name = "GPT OSS Safeguard 20B",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.07, .output = 0.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "qwen.qwen3-235b-a22b-2507-v1:0",
        .name = "Qwen3 235B A22B 2507",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.22, .output = 0.88, .cache_read = 0, .cache_write = 0 },
        .context_window = 262144,
        .max_tokens = 131072,
    });
    try registry.register(.{
        .id = "qwen.qwen3-32b-v1:0",
        .name = "Qwen3 32B (dense)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 16384,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "qwen.qwen3-coder-30b-a3b-v1:0",
        .name = "Qwen3 Coder 30B A3B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0, .cache_write = 0 },
        .context_window = 262144,
        .max_tokens = 131072,
    });
    try registry.register(.{
        .id = "qwen.qwen3-coder-480b-a35b-v1:0",
        .name = "Qwen3 Coder 480B A35B Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.22, .output = 1.8, .cache_read = 0, .cache_write = 0 },
        .context_window = 131072,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "qwen.qwen3-next-80b-a3b",
        .name = "Qwen/Qwen3-Next-80B-A3B-Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.14, .output = 1.4, .cache_read = 0, .cache_write = 0 },
        .context_window = 262000,
        .max_tokens = 262000,
    });
    try registry.register(.{
        .id = "qwen.qwen3-vl-235b-a22b",
        .name = "Qwen/Qwen3-VL-235B-A22B-Instruct",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = false,
        .cost = .{ .input = 0.3, .output = 1.5, .cache_read = 0, .cache_write = 0 },
        .context_window = 262000,
        .max_tokens = 262000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-haiku-4-5-20251001-v1:0",
        .name = "Claude Haiku 4.5 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-opus-4-1-20250805-v1:0",
        .name = "Claude Opus 4.1 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-opus-4-20250514-v1:0",
        .name = "Claude Opus 4 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-opus-4-5-20251101-v1:0",
        .name = "Claude Opus 4.5 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-opus-4-6-v1",
        .name = "Claude Opus 4.6 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-sonnet-4-20250514-v1:0",
        .name = "Claude Sonnet 4 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        .name = "Claude Sonnet 4.5 (US)",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "writer.palmyra-x4-v1:0",
        .name = "Palmyra X4",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 0, .cache_write = 0 },
        .context_window = 122880,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "writer.palmyra-x5-v1:0",
        .name = "Palmyra X5",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.6, .output = 6, .cache_read = 0, .cache_write = 0 },
        .context_window = 1040000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "zai.glm-4.7",
        .name = "GLM-4.7",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.6, .output = 2.2, .cache_read = 0, .cache_write = 0 },
        .context_window = 204800,
        .max_tokens = 131072,
    });
    try registry.register(.{
        .id = "zai.glm-4.7-flash",
        .name = "GLM-4.7-Flash",
        .api = "bedrock-converse-stream",
        .provider = "amazon-bedrock",
        .base_url = "https://bedrock-runtime.us-east-1.amazonaws.com",
        .reasoning = true,
        .cost = .{ .input = 0.07, .output = 0.4, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 131072,
    });
    try registry.register(.{
        .id = "claude-3-5-haiku-20241022",
        .name = "Claude Haiku 3.5",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 0.8, .output = 4, .cache_read = 0.08, .cache_write = 1 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "claude-3-5-haiku-latest",
        .name = "Claude Haiku 3.5 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 0.8, .output = 4, .cache_read = 0.08, .cache_write = 1 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "claude-3-5-sonnet-20240620",
        .name = "Claude Sonnet 3.5",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "claude-3-5-sonnet-20241022",
        .name = "Claude Sonnet 3.5 v2",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "claude-3-7-sonnet-20250219",
        .name = "Claude Sonnet 3.7",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-3-7-sonnet-latest",
        .name = "Claude Sonnet 3.7 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-3-haiku-20240307",
        .name = "Claude Haiku 3",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 0.25, .output = 1.25, .cache_read = 0.03, .cache_write = 0.3 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "claude-3-opus-20240229",
        .name = "Claude Opus 3",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "claude-3-sonnet-20240229",
        .name = "Claude Sonnet 3",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = false,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 0.3 },
        .context_window = 200000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "claude-haiku-4-5",
        .name = "Claude Haiku 4.5 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-haiku-4-5-20251001",
        .name = "Claude Haiku 4.5",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 1, .output = 5, .cache_read = 0.1, .cache_write = 1.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-opus-4-0",
        .name = "Claude Opus 4 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "claude-opus-4-1",
        .name = "Claude Opus 4.1 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "claude-opus-4-1-20250805",
        .name = "Claude Opus 4.1",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "claude-opus-4-20250514",
        .name = "Claude Opus 4",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 75, .cache_read = 1.5, .cache_write = 18.75 },
        .context_window = 200000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "claude-opus-4-5",
        .name = "Claude Opus 4.5 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-opus-4-5-20251101",
        .name = "Claude Opus 4.5",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-opus-4-6",
        .name = "Claude Opus 4.6",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 5, .output = 25, .cache_read = 0.5, .cache_write = 6.25 },
        .context_window = 200000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "claude-sonnet-4-0",
        .name = "Claude Sonnet 4 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-sonnet-4-20250514",
        .name = "Claude Sonnet 4",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-sonnet-4-5",
        .name = "Claude Sonnet 4.5 (latest)",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "claude-sonnet-4-5-20250929",
        .name = "Claude Sonnet 4.5",
        .api = "anthropic-messages",
        .provider = "anthropic",
        .base_url = "https://api.anthropic.com",
        .reasoning = true,
        .cost = .{ .input = 3, .output = 15, .cache_read = 0.3, .cache_write = 3.75 },
        .context_window = 200000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "codex-mini-latest",
        .name = "Codex Mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.5, .output = 6, .cache_read = 0.375, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "gpt-4",
        .name = "GPT-4",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 30, .output = 60, .cache_read = 0, .cache_write = 0 },
        .context_window = 8192,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gpt-4-turbo",
        .name = "GPT-4 Turbo",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 10, .output = 30, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "gpt-4.1",
        .name = "GPT-4.1",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4.1-mini",
        .name = "GPT-4.1 mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 0.4, .output = 1.6, .cache_read = 0.1, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4.1-nano",
        .name = "GPT-4.1 nano",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.03, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4o",
        .name = "GPT-4o",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-05-13",
        .name = "GPT-4o (2024-05-13)",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 5, .output = 15, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-08-06",
        .name = "GPT-4o (2024-08-06)",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-11-20",
        .name = "GPT-4o (2024-11-20)",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-mini",
        .name = "GPT-4o mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0.08, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5",
        .name = "GPT-5",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-chat-latest",
        .name = "GPT-5 Chat Latest",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = false,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5-codex",
        .name = "GPT-5-Codex",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-mini",
        .name = "GPT-5 Mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 0.25, .output = 2, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-nano",
        .name = "GPT-5 Nano",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 0.05, .output = 0.4, .cache_read = 0.005, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-pro",
        .name = "GPT-5 Pro",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 120, .cache_read = 0, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 272000,
    });
    try registry.register(.{
        .id = "gpt-5.1",
        .name = "GPT-5.1",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.13, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-chat-latest",
        .name = "GPT-5.1 Chat",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex",
        .name = "GPT-5.1 Codex",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-max",
        .name = "GPT-5.1 Codex Max",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-mini",
        .name = "GPT-5.1 Codex mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 0.25, .output = 2, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2",
        .name = "GPT-5.2",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2-chat-latest",
        .name = "GPT-5.2 Chat",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5.2-codex",
        .name = "GPT-5.2 Codex",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2-pro",
        .name = "GPT-5.2 Pro",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 21, .output = 168, .cache_read = 0, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex",
        .name = "GPT-5.3 Codex",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex-spark",
        .name = "GPT-5.3 Codex Spark",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "o1",
        .name = "o1",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 60, .cache_read = 7.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o1-pro",
        .name = "o1-pro",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 150, .output = 600, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3",
        .name = "o3",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-deep-research",
        .name = "o3-deep-research",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 10, .output = 40, .cache_read = 2.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-mini",
        .name = "o3-mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.1, .output = 4.4, .cache_read = 0.55, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-pro",
        .name = "o3-pro",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 20, .output = 80, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o4-mini",
        .name = "o4-mini",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 1.1, .output = 4.4, .cache_read = 0.28, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o4-mini-deep-research",
        .name = "o4-mini-deep-research",
        .api = "azure-openai-responses",
        .provider = "azure-openai-responses",
        .base_url = "",
        .reasoning = true,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "gemini-1.5-flash",
        .name = "Gemini 1.5 Flash",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = false,
        .cost = .{ .input = 0.075, .output = 0.3, .cache_read = 0.01875, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gemini-1.5-flash-8b",
        .name = "Gemini 1.5 Flash-8B",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = false,
        .cost = .{ .input = 0.0375, .output = 0.15, .cache_read = 0.01, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gemini-1.5-pro",
        .name = "Gemini 1.5 Pro",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = false,
        .cost = .{ .input = 1.25, .output = 5, .cache_read = 0.3125, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gemini-2.0-flash",
        .name = "Gemini 2.0 Flash",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = false,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gemini-2.0-flash-lite",
        .name = "Gemini 2.0 Flash Lite",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = false,
        .cost = .{ .input = 0.075, .output = 0.3, .cache_read = 0, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash",
        .name = "Gemini 2.5 Flash",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.3, .output = 2.5, .cache_read = 0.075, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-lite",
        .name = "Gemini 2.5 Flash Lite",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-lite-preview-06-17",
        .name = "Gemini 2.5 Flash Lite Preview 06-17",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-lite-preview-09-2025",
        .name = "Gemini 2.5 Flash Lite Preview 09-25",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-preview-04-17",
        .name = "Gemini 2.5 Flash Preview 04-17",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0.0375, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-preview-05-20",
        .name = "Gemini 2.5 Flash Preview 05-20",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0.0375, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-flash-preview-09-2025",
        .name = "Gemini 2.5 Flash Preview 09-25",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.3, .output = 2.5, .cache_read = 0.075, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-pro",
        .name = "Gemini 2.5 Pro",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.31, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-pro-preview-05-06",
        .name = "Gemini 2.5 Pro Preview 05-06",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.31, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-2.5-pro-preview-06-05",
        .name = "Gemini 2.5 Pro Preview 06-05",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.31, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-3-flash-preview",
        .name = "Gemini 3 Flash Preview",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.5, .output = 3, .cache_read = 0.05, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-3-pro-preview",
        .name = "Gemini 3 Pro Preview",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 2, .output = 12, .cache_read = 0.2, .cache_write = 0 },
        .context_window = 1000000,
        .max_tokens = 64000,
    });
    try registry.register(.{
        .id = "gemini-flash-latest",
        .name = "Gemini Flash Latest",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.3, .output = 2.5, .cache_read = 0.075, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-flash-lite-latest",
        .name = "Gemini Flash-Lite Latest",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 1048576,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "gemini-live-2.5-flash",
        .name = "Gemini Live 2.5 Flash",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.5, .output = 2, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 8000,
    });
    try registry.register(.{
        .id = "gemini-live-2.5-flash-preview-native-audio",
        .name = "Gemini Live 2.5 Flash Preview Native Audio",
        .api = "google-generative-ai",
        .provider = "google",
        .base_url = "https://generativelanguage.googleapis.com/v1beta",
        .reasoning = true,
        .cost = .{ .input = 0.5, .output = 2, .cache_read = 0, .cache_write = 0 },
        .context_window = 131072,
        .max_tokens = 65536,
    });
    try registry.register(.{
        .id = "k2p5",
        .name = "Kimi K2.5",
        .api = "anthropic-messages",
        .provider = "kimi-coding",
        .base_url = "https://api.kimi.com/coding",
        .reasoning = true,
        .cost = .{ .input = 0, .output = 0, .cache_read = 0, .cache_write = 0 },
        .context_window = 262144,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "kimi-k2-thinking",
        .name = "Kimi K2 Thinking",
        .api = "anthropic-messages",
        .provider = "kimi-coding",
        .base_url = "https://api.kimi.com/coding",
        .reasoning = true,
        .cost = .{ .input = 0, .output = 0, .cache_read = 0, .cache_write = 0 },
        .context_window = 262144,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "codex-mini-latest",
        .name = "Codex Mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.5, .output = 6, .cache_read = 0.375, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "gpt-4",
        .name = "GPT-4",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 30, .output = 60, .cache_read = 0, .cache_write = 0 },
        .context_window = 8192,
        .max_tokens = 8192,
    });
    try registry.register(.{
        .id = "gpt-4-turbo",
        .name = "GPT-4 Turbo",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 10, .output = 30, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "gpt-4.1",
        .name = "GPT-4.1",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4.1-mini",
        .name = "GPT-4.1 mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 0.4, .output = 1.6, .cache_read = 0.1, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4.1-nano",
        .name = "GPT-4.1 nano",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 0.1, .output = 0.4, .cache_read = 0.03, .cache_write = 0 },
        .context_window = 1047576,
        .max_tokens = 32768,
    });
    try registry.register(.{
        .id = "gpt-4o",
        .name = "GPT-4o",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-05-13",
        .name = "GPT-4o (2024-05-13)",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 5, .output = 15, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 4096,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-08-06",
        .name = "GPT-4o (2024-08-06)",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-2024-11-20",
        .name = "GPT-4o (2024-11-20)",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 2.5, .output = 10, .cache_read = 1.25, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-4o-mini",
        .name = "GPT-4o mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 0.15, .output = 0.6, .cache_read = 0.08, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5",
        .name = "GPT-5",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-chat-latest",
        .name = "GPT-5 Chat Latest",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = false,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5-codex",
        .name = "GPT-5-Codex",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-mini",
        .name = "GPT-5 Mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 0.25, .output = 2, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-nano",
        .name = "GPT-5 Nano",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 0.05, .output = 0.4, .cache_read = 0.005, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5-pro",
        .name = "GPT-5 Pro",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 120, .cache_read = 0, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 272000,
    });
    try registry.register(.{
        .id = "gpt-5.1",
        .name = "GPT-5.1",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.13, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-chat-latest",
        .name = "GPT-5.1 Chat",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex",
        .name = "GPT-5.1 Codex",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-max",
        .name = "GPT-5.1 Codex Max",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-mini",
        .name = "GPT-5.1 Codex mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 0.25, .output = 2, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2",
        .name = "GPT-5.2",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2-chat-latest",
        .name = "GPT-5.2 Chat",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 16384,
    });
    try registry.register(.{
        .id = "gpt-5.2-codex",
        .name = "GPT-5.2 Codex",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2-pro",
        .name = "GPT-5.2 Pro",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 21, .output = 168, .cache_read = 0, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex",
        .name = "GPT-5.3 Codex",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 400000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex-spark",
        .name = "GPT-5.3 Codex Spark",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 32000,
    });
    try registry.register(.{
        .id = "o1",
        .name = "o1",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 15, .output = 60, .cache_read = 7.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o1-pro",
        .name = "o1-pro",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 150, .output = 600, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3",
        .name = "o3",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-deep-research",
        .name = "o3-deep-research",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 10, .output = 40, .cache_read = 2.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-mini",
        .name = "o3-mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.1, .output = 4.4, .cache_read = 0.55, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o3-pro",
        .name = "o3-pro",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 20, .output = 80, .cache_read = 0, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o4-mini",
        .name = "o4-mini",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 1.1, .output = 4.4, .cache_read = 0.28, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "o4-mini-deep-research",
        .name = "o4-mini-deep-research",
        .api = "openai-responses",
        .provider = "openai",
        .base_url = "https://api.openai.com/v1",
        .reasoning = true,
        .cost = .{ .input = 2, .output = 8, .cache_read = 0.5, .cache_write = 0 },
        .context_window = 200000,
        .max_tokens = 100000,
    });
    try registry.register(.{
        .id = "gpt-5.1",
        .name = "GPT-5.1",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-max",
        .name = "GPT-5.1 Codex Max",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 1.25, .output = 10, .cache_read = 0.125, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.1-codex-mini",
        .name = "GPT-5.1 Codex Mini",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 0.25, .output = 2, .cache_read = 0.025, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2",
        .name = "GPT-5.2",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.2-codex",
        .name = "GPT-5.2 Codex",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex",
        .name = "GPT-5.3 Codex",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 1.75, .output = 14, .cache_read = 0.175, .cache_write = 0 },
        .context_window = 272000,
        .max_tokens = 128000,
    });
    try registry.register(.{
        .id = "gpt-5.3-codex-spark",
        .name = "GPT-5.3 Codex Spark",
        .api = "openai-codex-responses",
        .provider = "openai-codex",
        .base_url = "https://chatgpt.com/backend-api",
        .reasoning = true,
        .cost = .{ .input = 0, .output = 0, .cache_read = 0, .cache_write = 0 },
        .context_window = 128000,
        .max_tokens = 128000,
    });
}

test "generated source is non-empty" {
    try std.testing.expect(true);
}
